### ISSUE TITLE
questions about input resolution and self-shadow

### ISSUE THREAD

**Issue by maxqiqq** [fvasluianu97/WSRD-DNSR#1]
Hello, I appreciate your willingness to share the code. After reading the paper, I still have two areas of confusion and would greatly appreciate your response.
1) The paper states that the research intention is to "study more complex light interaction model which includes self-shadow", yet self-shadow is avoided in the capture setup. this makes me confused.
2) The high-resolution input in the paper is 1920*1440. What impact will there be if I input a higher resolution (such as 2048^2)? Will the aspect ratio of the image also affects ?

Thank you very much for your help.

**Comment by fvasluianu97** [comment]
Self shadows are avoided only in the ground-truth image acquisition. 
The resolution is not really a factor (although in the SHARDS paper the authors claim that the task becomes more complex at HR), from our experience, the performance loss is marginal.

**Comment by maxqiqq** [comment]
alright, thx for your reply:D
