### ISSUE TITLE
questions about the code

### ISSUE THREAD

**Issue by maxqiqq** [fvasluianu97/WSRD-DNSR#2]
After studying your code, I have the following questions to ask:

1. If I want to perform shadow removal on 2048^2 images using your network, what parameters should I pay attention to? What should I choose for the fullres parameter?

2. What are the main differences between the UNet and DistillNet structures provided in the code? How should I choose?

3. Could you provide a relevant environment configuration file? 

I’m a beginner and am constantly learning. Thank you for your patience and response.

**Comment by fvasluianu97** [comment]
1. Details are provided in the following paper: https://openaccess.thecvf.com/content/CVPR2023W/NTIRE/papers/Vasluianu_WSRD_A_Novel_Benchmark_for_High_Resolution_Image_Shadow_Removal_CVPRW_2023_paper.pdf.
2. For high resolution images the main limitation is the available GPU VRAM amount. You can think about various solutions, such as applying the inference on a lowered resolution image that will be then upscaled, or you can tile the image then applying inference on different patches of it. 
3. There is no configuration file needed to run this project. Parameters are provided in the manuscript linked above, and they are customizable by command line arguments.
